name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install, lint, test and build
        run: |
          npx yarn install
          npx yarn run prettier-check
          npx yarn run lint
          npx yarn run build-lib
          npx yarn run typecheck
        env:
          CI: true
